name: Compile Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '20'

    - name: Build with Maven
      run: mvn clean compile

    - name: Check if compilation passed
      run: echo "Compilation successful"
